version: "3"

services:
  pihole-broken:
    image: pihole/pihole:2021.11
    ports:
      - "9080:80/tcp"
    environment:
      TZ: 'America/New_York'
      DNS1: '127.0.0.1#8080'
      DNS2: 'no'
      WEBPASSWORD: 'password'
    volumes:
      - './etc-pihole-broken/:/etc/pihole/'

  pihole-fixed:
    build:
      context: .
    ports:
      - "9081:80/tcp"
    environment:
      TZ: 'America/New_York'
      DNS1: '127.0.0.1#8080'
      DNS2: 'no'
      WEBPASSWORD: 'password'
    volumes:
      - './etc-pihole-fixed/:/etc/pihole/'

  pihole-test:
    image: pihole/pihole:special-core-tweak-gravity
    ports:
      - "9082:80/tcp"
    environment:
      TZ: 'America/New_York'
      DNS1: '127.0.0.1#8080'
      DNS2: 'no'
      WEBPASSWORD: 'password'
    volumes:
      - './etc-pihole-test/:/etc/pihole/'
